/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backup;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;

public class Backup {
	private static final String className = Backup.class.getSimpleName();
	private static final DateTimeFormatter folderFormat = DateTimeFormatter.ofPattern("yyyyMMMdd hhmmss");

	public static void main(String[] args) {
		System.out.println("##### Starting " + className + " #####\n");

		try {
			Scanner scanner = new Scanner(new File("config.csv"));
			scanner.nextLine();
			String now = LocalDateTime.now().format(folderFormat);

			while (scanner.hasNext()) {
				String[] line = scanner.nextLine().split(",");
				Path source = Paths.get(line[0]);
				Path target = Paths.get(line[1]).resolve(now);

				Files.createDirectories(target);
				Files.copy(source, target.resolve(source.getFileName()));
				System.out.println("Backing up '" + source + "' to '" + target + "'");
			}
		} catch (IOException e) {
			System.out.println("Backup failed!");
		}

		System.out.println("\n##### " + className + " completed #####");
	}
}
